model_0:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold0_segFalse
  file_name: cuda_model_auroc.ts
  device: 0

model_4:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold4_segFalse
  file_name: cuda_model_auroc.ts
  device: 0

model_5:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold5_segFalse
  file_name: cuda_model_auroc.ts
  device: 0
