model_0:
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold3
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

model_1:
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold5
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"