model_0:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold3
  file_name: cuda_model.ts
  device: 0

model_1:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold5
  file_name: cuda_model.ts
  device: 0
