model_0:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold0_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_1:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold1_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_2:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold2_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_3:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold3_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_4:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold4_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_5:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold5_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_6:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold6_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_7:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold7_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_8:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold8_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_9:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold9_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_10:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold10_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_11:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold11_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_12:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold12_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_13:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold13_15CV
  file_name: cuda_model_auroc.ts
  device: 0

model_14:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold14_15CV
  file_name: cuda_model_auroc.ts
  device: 0
