model_0:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold0_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: 0

model_1:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold1_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: 0

model_2:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold2_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: 0

model_3:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold3_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: 0

model_4:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold4_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: 0

model_5:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold5_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: 0

model_6:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold6_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: 0
