_target_: torch.utils.data.DataLoader

dataset:
  _target_: trainer.downstream.datasets.luna25.CTCaseDataset
  mode: train
  mode_model: 3D
  data_dir: /team/team_blu3/lung/data/2_public/LUNA25_Original/luna25_nodule_blocks
  fetch_from_patch: True
  dicom_window: [ "BASE" ]
  translations: True
  rotations: ((0, 1), (0, 1), (-20, 20))  # originally, it was ((-20, 20), (-20, 20), (-20, 20)).
  size_xy: 128
  size_z: 64
  size_mm: 50
  size_px_xy: 72
  size_px_z: 48
  use_weighted_sampler: true
  interpolate_order: 1

  # augmentation
  augmentation:
    dicom_windowing:
      aug_prob: 0.5
      level_shift:
        min: -100.0
        max: 100.0
      width_scale:
        min: 0.9
        max: 1.1
    flip_xy:
      aug_prob: 0.5
    flip_3d:
      aug_prob: 0.5
    coarse_dropout_3d:
      aug_prob: 0.2
      max_holes: 12
    rescale_image_3d:
      aug_prob: 0.0
      is_same_across_axes: True
      scale_factor:
        min: 0.5
        max: 2.0

  # target_dataset list should be selected between ['luna16_neg', 'luna16_pos', 'segmed', 'asan', 'adeno']
  target_dataset_train: [ 'luna25' ]
  target_dataset_val_test: [ 'luna25' ]

  # dataset query 작성에 유의할 것! 특히 '-' 유무도 에러에 영향을 줄 수 있음.
  dataset_infos:
    luna25:
      total_fold: [ 0, 1, 2, 3, 4, 5, 6 ]
      val_fold: [ ]
      test_fold: [ 0, 1, 2, 3, 4, 5, 6 ]
      fold_key: fold  # one of {fold, fold_10, fold_15}
      collection_name: LUNA25-Malignancy-Feature
      query:

batch_size: 32
num_workers: 4
pin_memory: True
prefetch_factor: 4
drop_last: False
