# specify default configuration
defaults:
  - loader: lidc
  - processor: processor_lidc
  - models: 4_0_1rc3.yaml

run_name: "4_0_1rc3_lidc_eval"
run_modes:
  - test
sanity_check: False
update_docs: False

hydra:
  run:
    dir: ./outputs/inference_results_lidc
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
