result_csv_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.3-beta-v1/result_2_0_3.csv
sort_criterion: prob_ensemble

hydra:
  run:
    dir: ./outputs/visualization_result
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
