best_csv: "/team/team_blu3/lung/project/luna25/analysis/inference_results_combined/result_5_0_8rc2.csv"
compare_csv: "/team/team_blu3/lung/project/luna25/analysis/inference_results_combined/result_5_0_9rc8.csv"
mode: luna25  # one of { luna25, lidc }
topk_num_sample: 20

hydra:
  run:
    dir: ./outputs/visualization_diff_result
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
