# specify default training configuration
defaults:
  - loader: default
  - processor: default
  - models: 2_0_1.yaml

run_modes:
  - val
  - test
sanity_check: False

hydra:
  run:
    dir: ./outputs
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
