# specify default configuration
defaults:
  - loader: lidc_mask2
  - processor: default
  - models: 5_0_9rc4.yaml

run_name: "5_0_9rc4"
run_modes:
  - test

sanity_check: False

# LR weights configuration
is_lr_weight: false  # default is false
lr_weights_path: "/opt/challenge/analyzer/malignancy/outputs/inference_results/5_0_2rc2/outputs/lr_ensemble_weights_5_0_2rc2.json"

hydra:
  run:
    dir: ./outputs/inference_results_lidc
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
