run_name: "5_0_9rc3"
result_csv_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.9rc3/result_5_0_9rc3.csv  # result_{run_name}.csv

hydra:
  run:
    dir: ./outputs/failure_analysis_result
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
