# specify default configuration
defaults:
  - loader: default
  - processor: default
  - models: 5_0_2rc2.yaml

run_name: "4_0_1rc3"
run_modes:
  - test

do_tta_by_size: False
sanity_check: False

result_csv_path: "/opt/challenge/analyzer/malignancy/outputs/inference_results_lidc/result_2_3_1rc2_lidc_eval.csv"

hydra:
  run:
    dir: ./outputs/inference_results_lidc/2_3_1rc2
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
