# specify default configuration
defaults:
  - loader: default
  - processor: default
  - models: 5_0_9rc3.yaml

run_name: "5_0_9rc3"
run_modes:
  - test

do_tta_by_size: False
sanity_check: False

hydra:
  run:
    dir: ./outputs/inference_results
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
