# specify default configuration
defaults:
  - loader: lidc_mask2
  - processor: default
  - models: 5_0_8rc2_weighted.yaml

run_name: "5_0_8rc2_weighted"
run_modes:
  - test

sanity_check: False

hydra:
  run:
    dir: ./outputs/inference_results_lidc
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
