result_csv_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.3rc2/result_5_0_3rc2.csv  # result_{run_name}.csv
sort_criterion: prob_ensemble

hydra:
  run:
    dir: ./outputs/visualization_result
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
