run_name: "5_0_8rc2"
result_csv_path: "/team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.8rc2/result_5_0_8rc2.csv"
save_into_shared_lib: True

hydra:
  run:
    dir: ./outputs/model_weights
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
