# specify default training configuration
defaults:
  - loader: default
  - processor: default
  - models: 2_0_1.yaml

run_name: "2_0_1"
run_modes:
  - test
sanity_check: False
output_dir: ./results

hydra:
  run:
    dir: ./outputs
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
