# specify default configuration
defaults:
  - loader: combined.yaml
  - processor: default
  - models: 5_0_9rc7.yaml

run_name: "5_0_9rc7"
run_modes:
  - test

do_tta_by_size: False
sanity_check: False

hydra:
  run:
    dir: ./outputs/inference_results_combined
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
