model_repr:
  _target_: trainer.common.models.unet_3d_MS.Model
  in_channels: 1
  f_maps: 48
  num_levels: 4
  num_groups: 4
  layer_order: gcr
  return_downstream_logit: False
  return_named_tuple: False
  classifier:
    _target_: trainer.common.models.modules.classifier.Classifier
    in_planes: 192
    out_planes: 1
    drop_prob: 0.05
    target_attr_total: ${trainer.target_attr_total}
    target_attr_to_train: ${trainer.target_attr_to_train}
    target_attr_downstream: ${trainer.target_attr_downstream}
    return_logit: False
