model_0:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg
  exp_name: cls_all_model_5_val_fold0
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"
