model_0:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_final
  exp_name: cls_all_model_6_val_fold0_7CV
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_1:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_final
  exp_name: cls_all_model_6_val_fold1_7CV
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_2:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_final
  exp_name: cls_all_model_6_val_fold2_7CV
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_3:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_final
  exp_name: cls_all_model_6_val_fold3_7CV
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_4:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_final
  exp_name: cls_all_model_6_val_fold4_7CV
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_5:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_final
  exp_name: cls_all_model_6_val_fold5_7CV
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_6:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_final
  exp_name: cls_all_model_6_val_fold6_7CV
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"
