model_0:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_KD_7CV
  exp_name: cls_all_KD_val_fold0
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_1:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_KD_7CV
  exp_name: cls_all_KD_val_fold1
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_2:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_KD_7CV
  exp_name: cls_all_KD_val_fold2
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_3:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_KD_7CV
  exp_name: cls_all_KD_val_fold3
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_4:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_KD_7CV
  exp_name: cls_all_KD_val_fold4
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_5:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_KD_7CV
  exp_name: cls_all_KD_val_fold5
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_6:
  _target_: shared_lib.model_runner.nodule_attr_runner.NoduleAttrRunner
  root_path: /team/team_blu3/lung/project/luna25/pretrained/nodule_attr_seg_KD_7CV
  exp_name: cls_all_KD_val_fold6
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"
