# syntax=docker/dockerfile:1.4

# Dockerfile for dev image to each person.
# Usage : docker build --tag vunolungteam/vuno-lung-cad-server:dev_${USER} -f Dockerfile_dev . \
# --build-arg USER_ID=$(id -u ${USER}) --build-arg GROUP_ID=$(id -g ${USER})
# "base" tag is set in build_check.yaml github action

FROM vunolungteam/vuno-lung-research:base
MAINTAINER mi.chest@vuno.co

# https://jtreminio.com/blog/running-docker-containers-as-current-host-user/
# --build-arg USER_ID=$(id -u ${USER})
# --build-arg GROUP_ID=$(id -g ${USER})
ARG USER_ID
ARG GROUP_ID

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  rsync \
  tmux \
  wget \
  zsh && \
  rm -rf /var/lib/apt/lists/*

# Add the PPA and install nvtop
RUN add-apt-repository ppa:flexiondotorg/nvtop && \
  apt-get update && \
  apt-get install -y nvtop && \
  rm -rf /var/lib/apt/lists/*

RUN groupadd -g ${GROUP_ID} lungteam
RUN useradd -l -u ${USER_ID} -g lungteam -p $(openssl passwd -1 vuno2018) vuno
RUN echo "vuno ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN mkdir -p /usr/src/vuno_lung_CAD
RUN mkdir /home/vuno
RUN export HOME=/home/vuno
RUN chown -R vuno:lungteam /home/vuno
USER vuno

# Install requirements for dev
RUN pip3 install --upgrade pip
COPY requirements_dev.txt /usr/local/requirements_dev.txt
RUN pip3 install --no-cache-dir --no-deps -r /usr/local/requirements_dev.txt

# Enable mouse scrolling for tmux by uncommenting.
# iTerm2 users should change settings to use scrolling properly.
RUN echo 'set -g mouse on' >> ${HOME}/.tmux.conf

WORKDIR /usr/src/vuno_lung_CAD

# install oh-my-zsh 
SHELL ["/bin/zsh", "-c"]
RUN sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

RUN git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
RUN perl -pi -w -e 's/ZSH_THEME=.*/ZSH_THEME="agnoster"/g;' ~/.zshrc 
RUN perl -pi -w -e 's/plugins=.*/plugins=(git ssh-agent zsh-autosuggestions zsh-syntax-highlighting)/g;' ~/.zshrc
CMD ["/bin/zsh"]

