_target_: trainer.downstream.train.Trainer

# hyper params
max_epoch: 50
early_stop_patience: null

grad_clip_max_norm: 1.0

# loss, threshold
thresholding_mode_representative: youden
thresholding_mode: all

# operation
gpus: auto
log_every_n_steps: 50
test_epoch_start: ${trainer.max_epoch}
resume_from_checkpoint: null

fast_dev_run: False

# pretrained model
fine_tune_info:
  enable: False
  freeze_encoder: False
  pretrained_weight_path:
