_target_: trainer.downstream.train.Trainer

# hyper params
max_epoch: 30
early_stop_patience: null

grad_clip_max_norm: 1.0

# loss, threshold
thresholding_mode_representative: youden
thresholding_mode: all

# operation
gpus: auto
log_every_n_steps: 50
test_epoch_start: ${trainer.max_epoch}
resume_from_checkpoint: null
benchmark: False
deterministic: True
fast_dev_run: False
use_amp: False

# the total attributes interested
target_attr_total: [ 'c_subtlety_logistic', 'c_sphericity_logistic', 'c_lobulation_logistic', 'c_spiculation_logistic',
                     'c_margin_logistic', 'c_texture_logistic',
                     'c_calcification_logistic', 'c_internalStructure_logistic', 'c_malignancy_logistic' ]

# attributes to train
target_attr_to_train: [ 'c_malignancy_logistic' ]

# indication of downstream task
target_attr_downstream: 'c_malignancy_logistic'

# pretrained model
fine_tune_info:
  enable: False
  pretrained_encoder:
  freeze_encoder: True
