# specify default configuration
defaults:
  - loader: default
  - processor: default
  - models: nodule_attr_seg.yaml

run_name: "nodule_attr_seg"
run_modes:
  - val
  - test
sanity_check: False

hydra:
  run:
    dir: ./outputs/inference_results
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
