model_C:
  _target_: projects.downstream.models.resnest_bifpn.ResBiNet
  backbone:
    _target_: projects.downstream.models.modules.backbone.BackBone
    model_depth: 34
    in_planes: [48, 64, 96]
    widen_factor: 1.0
    block_cfg:
      cardinality: 1
      avd: True
      avd_first: False
      radix: 2
  neck:
    _target_: projects.downstream.models.modules.neck.Neck
    encoder_channels: ${model.model_C.backbone.in_planes}  # Number of channels for each feature map from low res to high res
    widen_factor: ${model.model_C.backbone.widen_factor}
    pyramid_channels: ${model.model_C.head.in_planes_head}
    num_fpn_layers: 1
    output_feature_index: 2
  head:
    _target_: projects.downstream.models.modules.head.Head
    in_planes_head: 512
    drop_out_prob: 0.01
