scheduler_repr:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 3.0e-04
  epochs: ${trainer.max_epoch}
  steps_per_epoch: null
  total_steps: null
  pct_start: 0.2
  anneal_strategy: cos
  last_epoch: -1
  verbose: False
