_target_: trainer.multi_modal.train.Trainer

# hyper params
max_epoch: 20
early_stop_patience: null

grad_clip_max_norm: 1.0

# loss, threshold
thresholding_mode_representative: youden
thresholding_mode: all

# nodule attr
target_attr_total: [ 'c_subtlety_logistic', 'c_sphericity_logistic', 'c_lobulation_logistic', 'c_spiculation_logistic',
                     'c_margin_logistic', 'c_texture_logistic',
                     'c_calcification_logistic', 'c_internalStructure_logistic' ]

# operation
gpus: auto
log_every_n_steps: 50
test_epoch_start: ${trainer.max_epoch}
resume_from_checkpoint: null

fast_dev_run: False

# pretrained model
fine_tune_info:
  enable: False
  freeze_encoder: False
  pretrained_weight_path:
