# specify default training configuration
defaults:
  - _self_
  - trainer: default
  - loader: default.yaml
  - criterion: focal_loss
  - model: resnest_weighted_fusion
  - optim: adamw
  - scheduler: one_cycle_lr
  - experiment_tool: mlflow

run_modes:
  - train
  - val
  - test

# Add path to pretrained patch-level model that will be frozen
# TODO: Unable to access the specified path. Please ensure it is correctly set to the model path on the NFS
path_patch_model: /opt/challenge/trainer/downstream/outputs/scale_ablation/ablation_unet_3d_MS_scale_1.0_val_fold5/model_auroc.pth  # Please replace with actual path

hydra:
  run:
    dir: ./outputs/${experiment_tool.run_group}/${experiment_tool.run_name}
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
