model_0:
  _target_: shared_lib.model_runner.image_level_runner.ImageLevelRunner
  root_path: /opt/challenge/trainer/image_level/outputs/logit_level_resnest
  exp_name: resnest_logit_level_classifier_f_192_unet_f_24_lr_1e-4_scale_1.5_fold0
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_1:
  _target_: shared_lib.model_runner.image_level_runner.ImageLevelRunner
  root_path: /opt/challenge/trainer/image_level/outputs/logit_level_resnest
  exp_name: resnest_logit_level_classifier_f_192_unet_f_24_lr_1e-4_scale_1.5_fold1
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_2:
  _target_: shared_lib.model_runner.image_level_runner.ImageLevelRunner
  root_path: /opt/challenge/trainer/image_level/outputs/logit_level_resnest
  exp_name: resnest_logit_level_classifier_f_192_unet_f_24_lr_1e-4_scale_1.5_fold2
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_3:
  _target_: shared_lib.model_runner.image_level_runner.ImageLevelRunner
  root_path: /opt/challenge/trainer/image_level/outputs/logit_level_resnest
  exp_name: resnest_logit_level_classifier_f_192_unet_f_24_lr_1e-4_scale_1.5_fold3
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_4:
  _target_: shared_lib.model_runner.image_level_runner.ImageLevelRunner
  root_path: /opt/challenge/trainer/image_level/outputs/logit_level_resnest
  exp_name: resnest_logit_level_classifier_f_192_unet_f_24_lr_1e-4_scale_1.5_fold4
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda"

model_5:
  _target_: shared_lib.model_runner.image_level_runner.ImageLevelRunner
  root_path: /opt/challenge/trainer/image_level/outputs/logit_level_resnest
  exp_name: resnest_logit_level_classifier_f_192_unet_f_24_lr_1e-4_scale_1.5_fold5
  file_name: cuda_model_loss.ts
  device: cuda # e.g., "cpu" or "cuda" 