FROM --platform=linux/amd64 pytorch/pytorch AS example-algorithm-amd64

# Ensures that Python output to stdout/stderr is not buffered
ENV PYTHONUNBUFFERED=1

# Install system dependencies
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user
RUN groupadd -r user && useradd -m --no-log-init -r -g user user
USER user

# Create app directory
WORKDIR /opt/app

# Copy and install dependencies
COPY --chown=user:user requirements.txt /opt/app/
RUN python -m pip install \
    --no-cache-dir \
    --no-color \
    --requirement /opt/app/requirements.txt

# Set default user and working directory
USER user
WORKDIR /opt/app
