model_0:
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.0
  exp_name: cv_fine_val_fold0
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

model_1:
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.0
  exp_name: cv_fine_val_fold1
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

model_2:
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.0
  exp_name: cv_fine_val_fold2
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

model_3:
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.0
  exp_name: cv_fine_val_fold3
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

model_4:
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.0
  exp_name: cv_fine_val_fold4
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

model_5:
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.0
  exp_name: cv_fine_val_fold5
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"
