model_0:
  _target_: shared_lib.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.3-beta-v1
  exp_name: cv_fine_val_fold0_with_rescale
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

model_1:
  _target_: shared_lib.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.3-beta-v1
  exp_name: cv_fine_val_fold1_with_rescale
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

model_2:
  _target_: shared_lib.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.3-beta-v1
  exp_name: cv_fine_val_fold2_with_rescale
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

model_3:
  _target_: shared_lib.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.3-beta-v1
  exp_name: cv_fine_val_fold3_with_rescale
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

model_4:
  _target_: shared_lib.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.3-beta-v1
  exp_name: cv_fine_val_fold4_with_rescale
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

model_5:
  _target_: shared_lib.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.3-beta-v1
  exp_name: cv_fine_val_fold5_with_rescale
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"
