model_0:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.1
  exp_name: cv_fine_val_fold3
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

model_1:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v2.0.1
  exp_name: cv_fine_val_fold5
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"
