model_0:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold0_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_1:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold1_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_2:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold2_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_3:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold3_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_4:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold4_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_5:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold5_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_6:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold6_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_7:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold7_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_8:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold8_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_9:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold9_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_10:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold10_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_11:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold11_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_12:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold12_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_13:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold13_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"

model_14:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v4.0.1rc3
  exp_name: cv_fine_val_fold14_15CV
  file_name: cuda_model_final.ts
  device: cuda # e.g., "cpu" or "cuda"
