model_0:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.9rc8
  exp_name: cv_fine_model7_val_fold0_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.12130712923782398
model_1:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.9rc8
  exp_name: cv_fine_model7_val_fold1_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.17210978684931375
model_2:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.9rc8
  exp_name: cv_fine_model7_val_fold2_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.23867819521396882
model_3:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.9rc8
  exp_name: cv_fine_model7_val_fold3_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.059531498367009335
model_4:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.9rc8
  exp_name: cv_fine_model7_val_fold4_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.32666906142116026
model_5:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.9rc8
  exp_name: cv_fine_model7_val_fold5_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.11238254493071746
model_6:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.9rc8
  exp_name: cv_fine_model7_val_fold6_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.13598845064667311
