model_0:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.8rc2
  exp_name: cv_fine_model7_val_fold0_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.021619254583117756
model_1:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.8rc2
  exp_name: cv_fine_model7_val_fold1_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.20150558642243208
model_2:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.8rc2
  exp_name: cv_fine_model7_val_fold2_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.27468099744750246
model_3:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.8rc2
  exp_name: cv_fine_model7_val_fold3_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.21996568897882293
model_4:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.8rc2
  exp_name: cv_fine_model7_val_fold4_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.24045892460759158
model_5:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.8rc2
  exp_name: cv_fine_model7_val_fold5_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.18551013871848665
model_6:
  _target_: shared_lib.model_runner.malignancy_runner.MalignancyRunner
  root_path: /team/team_blu3/lung/project/luna25/weights/nodulex-v5.0.8rc2
  exp_name: cv_fine_model7_val_fold6_7CV_phase2
  file_name: cuda_model_auroc.ts
  device: cuda
  weight: 0.022926075908713216
