- _target_: analyzer.malignancy.model.MalignancyModel
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold0
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"

- _target_: analyzer.malignancy.model.MalignancyModel
  root_path: /opt/app/resources
  exp_name: cv_fine_val_fold1
  file_name: cuda_model.ts
  device: cuda # e.g., "cpu" or "cuda"
