# specify default configuration
defaults:
  - loader: default
  - processor: default
  - models: image_level_models

run_name: "image_level_inference"
run_modes:
  - val
  - test
sanity_check: False

hydra:
  run:
    dir: ./outputs/resnest_logit_level_classifier_f_192_unet_f_24_lr_1e-4_scale_1.5_fold
  job:
    chdir: True  # keep hydra = 1.1 change directory behavior
