model_repr:
  _target_: trainer.common.models.swin_classifier.swin_classifier
  in_channels: 1
  num_classes: 1
  depths: [1, 1, 1, 1]
  num_heads: [2, 2, 2, 2]
  feature_size: 8
  drop_rate: 0.01
  attn_drop_rate: 0.0
  dropout_path_rate: 0.0
  normalize: True
  spatial_dims: 3
