model_C:
  _target_: trainer.common.models.swin_unetr.SwinUNETRClassifier
  in_channels: 1
  num_classes: 1
  depths: [2, 2, 2, 2]
  num_heads: [3, 6, 12, 24]
  feature_size: 48
  drop_rate: 0.0
  attn_drop_rate: 0.0
  dropout_path_rate: 0.0
  normalize: True
  spatial_dims: 3
  