model_repr:
  _target_: trainer.common.models.swin_classifier.swin_classifier
  in_channels: 1
  num_classes: 1
  depths: [1, 1, 1, 1]
  num_heads: [2, 2, 2, 2]
  feature_size: 8
  drop_rate: 0.01
  attn_drop_rate: 0.0
  dropout_path_rate: 0.0
  normalize: True
  spatial_dims: 3
  classifier: #swin transformer [16,32,64,128,256]
    _target_: trainer.common.models.modules.classifier.Classifier
    in_planes: 128  # 실제 입력 특징 맵의 채널 수
    out_planes: 1  # 이진 분류를 위한 출력
    drop_prob: 0.05
    target_attr_total: [ 'c_subtlety_logistic', 'c_sphericity_logistic', 'c_lobulation_logistic', 'c_spiculation_logistic',
                         'c_margin_logistic', 'c_texture_logistic',
                         'c_calcification_logistic', 'c_internalStructure_logistic', 'c_malignancy_logistic' ]
    target_attr_to_train: [ 'c_malignancy_logistic' ]
    target_attr_downstream: 'c_malignancy_logistic'
    return_logit: false
    