model_C:
  _target_: trainer.common.models.unet_3d_MS.Model
  in_channels: 1
  f_maps: 8
  num_levels: 4
  num_groups: 4
  layer_order: gcr
  classifier:
    _target_: trainer.common.models.modules.classifier.MultiScaleAttnClassifier
    f_maps: ${model.model_C.f_maps}
    num_levels: ${model.model_C.num_levels}
    num_features: 3
    drop_prob: 0.05
    pyramid_channels: 128
    num_fpn_layers: 2
    target_attr: ${trainer.target_attr}
    target_attr_to_train: ${trainer.target_attr_to_train}
    use_gate: True
    use_coord: True
    use_fusion: True
