_target_: trainer.nodule_attr.criterion.AttrLoss
cls_criterion:
  _target_: trainer.common.criterions.cls_loss.ClsLoss
  gamma: 2
  use_alpha: True
  smoothing: 0.05
  target_attr: ${trainer.target_attr}
  target_attr_to_train: ${trainer.fine_tune_info.target_attr_to_train}
  loss_weight: 1.0

entropy_criterion:
  _target_: trainer.common.criterions.losses.EntropyLoss
  loss_weight: 0.1

aux_criterion:
  _target_: trainer.common.criterions.cls_loss.ClsLoss
  gamma: 2
  use_alpha: True
  smoothing: 0.05
  target_attr: ${trainer.target_attr}
  target_attr_to_train: ${trainer.fine_tune_info.target_attr_to_train}
  loss_weight: 0.0
