_target_: torch.utils.data.DataLoader

dataset:
  _target_: projects.downstream.datasets.luna25.CTCaseDataset
  mode: train
  patch_size: [ 48, 72, 72 ]
  dicom_window: [ "VUNO" ]  # "VUNO", "LUNG", "MEDIASTINAL", "BONE"

  # preprocessing
  buffer: 2
  val_shift_scale: 0
  dataset_size_scale_factor: 1.0
  smoothing: 0.01

  # augmentation
  augmentation:
    dicom_windowing:
      aug_prob: 0.5
      level_shift:
        min: -100.0
        max: 100.0
      width_scale:
        min: 0.9
        max: 1.1
    flip_xy:
      aug_prob: 0.5
    flip_3d:
      aug_prob: 0.5
    random_crop_3d:
      aug_prob: 1.0
    random_rotate_3d:
      aug_prob: 0.5
    coarse_dropout_3d:
      aug_prob: 0.5
      max_holes: 24
    rescale_image_3d:
      aug_prob: 0.5
      scale_factor:
        min: 0.5
        max: 2.0

  # target_dataset list should be selected between ['luna16_neg', 'luna16_pos', 'segmed', 'asan', 'adeno']
  target_dataset: [ 'luna25' ]

  # dataset query 작성에 유의할 것! 특히 '-' 유무도 에러에 영향을 줄 수 있음.
  dataset_infos:
    luna25:
      total_fold: [ 0, 1, 2, 3, 4, 5, 6 ]
      val_fold: [ 5 ]
      test_fold: [ 6 ]
      collection_name: LUNA25-Malignancy
      field_name_mapper:
        confidence_label: num_mask
        diameter_label: c_diameter_resampled
      used_ratio: 1

batch_size: 8
num_workers: 4
pin_memory: True
prefetch_factor: 2
drop_last: False

