_target_: torch.utils.data.DataLoader

dataset:
  _target_: projects.downstream.datasets.luna25.CTCaseDataset
  mode: train
  mode_model: 3D
  patch_size: [64, 128, 128]
  translations: True
  rotations: ((-20, 20), (-20, 20), (-20, 20))
  size_xy: 128
  size_z: 64
  size_mm: 50
  size_px: 64

  # augmentation
  augmentation:
    dicom_windowing:
      aug_prob: 0.5
      level_shift:
        min: -100.0
        max: 100.0
      width_scale:
        min: 0.9
        max: 1.1
    flip_xy:
      aug_prob: 0.5
    flip_3d:
      aug_prob: 0.5
    random_crop_3d:
      aug_prob: 1.0
    random_rotate_3d:
      aug_prob: 0.5
    coarse_dropout_3d:
      aug_prob: 0.5
      max_holes: 24
    rescale_image_3d:
      aug_prob: 0.5
      scale_factor:
        min: 0.5
        max: 2.0

  # target_dataset list should be selected between ['luna16_neg', 'luna16_pos', 'segmed', 'asan', 'adeno']
  target_dataset_train: [ 'luna25' ]
  target_dataset_val_test: [ 'luna25' ]

  # dataset query 작성에 유의할 것! 특히 '-' 유무도 에러에 영향을 줄 수 있음.
  dataset_infos:
    luna25:
      total_fold: [ 0, 1, 2, 3, 4, 5, 6 ]
      val_fold: [ 5 ]
      test_fold: [ 6 ]
      collection_name: LUNA25-Malignancy
      query:

batch_size: 32
num_workers: 4
pin_memory: True
prefetch_factor: 2
drop_last: False

